// <auto-generated />
using ChocoLux.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChocoLux.Migrations
{
    [DbContext(typeof(ChocoLuxContext))]
    [Migration("20250106032130_Social_06Jan25_v1")]
    partial class Social_06Jan25_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChocoLux.DataModels.Chocolate", b =>
                {
                    b.Property<int>("ChocolateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChocolateId"));

                    b.Property<int>("ChocolateAmmount")
                        .HasColumnType("int");

                    b.Property<string>("ChocolateImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChocolateIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ChocolateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ChocolatePrice")
                        .HasColumnType("float");

                    b.HasKey("ChocolateId");

                    b.ToTable("Chocolate");
                });

            modelBuilder.Entity("ChocoLux.DataModels.ContactUs", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("ChocoLux.DataModels.Social", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialId"));

                    b.Property<string>("SocialIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialId");

                    b.ToTable("Social");
                });

            modelBuilder.Entity("ChocoLux.DataModels.Testimonial", b =>
                {
                    b.Property<int>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialId"));

                    b.Property<string>("TestimonialDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TestimonialIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TestimonialThumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestimonialId");

                    b.ToTable("Testimonial");
                });
#pragma warning restore 612, 618
        }
    }
}
